# Generated by Django 3.1.3 on 2020-11-07 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackernewsapp', '0002_auto_20201107_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='your_comment',
            new_name='content',
        ),
    ]
